language: python
python:
  - "3.6"
before_install:
  - nvm install 7.4.0
  - nvm use 7.4.0
install:
  - npm install
  - pip install flake8
  - pip install -r requirements.txt

script:
  - npm run test
  - flake8 app.py
  - python3 tests.py

